# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rubyone_voice_postgres
    restart: always
    environment:
      POSTGRES_DB: rubyone_voice_db
      POSTGRES_USER: rubyone_user
      POSTGRES_PASSWORD: your_secure_password_here
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rubyone_network

volumes:
  postgres_data:
    driver: local

networks:
  rubyone_network:
    driver: bridge 